### ISSUE TITLE
SQS daemon requests are not intercepted

### ISSUE THREAD

**Issue by tawan** [tawan/active-elastic-job#10]

**Comment by zaaroth** [comment]
My worker environment is not playing nice with installing a gem from git. It seems to require more memory than your average gem (not sure why, though). Any plans to release an update with this?

**Comment by tawan** [comment]
Hi, yes in a couple of minutes. I'm just waiting for the build to finish.

**Comment by tawan** [comment]
https://travis-ci.org/tawan/active-elastic-job/builds/107602166

**Comment by tawan** [comment]
I released a new version. @zaaroth If this solves your problem, can you give a quick notice?

Cheers,

tawan

**Comment by zaaroth** [comment]
The events are now being consumed. I will perform an end to end test tomorrow to be sure, but chances are this is fixed.
