### ISSUE TITLE
Action mailer deliver_later does not work

### ISSUE THREAD

**Issue by bookmebus** [tawan/active-elastic-job#102]
I am migrating Sidekiq jot to Active Elastic Job in eb worker env. I am using Mandrill API to send transactional email to customers. 

```ruy
  # Deliver now works just fine
  Transit::ReservationMailer.notify_success(r.id).deliver_now
```
It received the email, however if I do this

```ruy
  # Deliver later put job in to background process
  Transit::ReservationMailer.notify_success(r.id).deliver_later
```
I got this back from production console

```ruby
Enqueued ActionMailer::DeliveryJob (Job ID: 2ede3145-6945-4704-bbe6-46f8411afe6a) to ActiveElasticJob(mailers) with arguments: "Transit::ReservationMailer", "notify_success", "deliver_now", 19098
[ActiveJob] Enqueued ActionMailer::DeliveryJob (Job ID: 2ede3145-6945-4704-bbe6-46f8411afe6a) to ActiveElasticJob(mailers) with arguments: "Transit::ReservationMailer", "notify_success", "deliver_now", 19098
=> #<ActionMailer::DeliveryJob:0x000055c70f5c3240 @arguments=["Transit::ReservationMailer", "notify_success", "deliver_now", 19098], @job_id="2ede3145-6945-4704-bbe6-46f8411afe6a", @queue_name="mailers">
```
A new queue added to Amazon SQS correctly but it seems that Active Elastic Job does not process the queue.

Is there anything wrong with my worker/gem setup? 

I've created 3 queues  ( default, mailers, cron ) for my applications.

**Comment by bookmebus** [comment]
solved. I have my worker connect to **default** queue. Surprisingly one worker can associate with one queue only. I have to have two workers or change my code to run under one queue name.

**Comment by joeyparis** [comment]
> Surprisingly one worker can associate with one queue only.
Ya, unfortunately, this does seem to be a limitation of ElasticBeanstalk which is kind of disappointing. I personally ended up just having all of my jobs run through one queue which although not ideal, works enough. Glad you got it solved though!
