### ISSUE TITLE
Applying new patches

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [tawan/active-elastic-job#106]
Hello guys,

We'll use Elastic Beanstalk with ActiveJob, and we found this awesome gem; however, it has some problems with CI (especially Ruby 2.4) and @tawan was not using Elastic Beanstalk anymore. Also, test files depend to real Elastic Beanstalk environment, but *I think*, we can achieve this problem with using stubbed data.

These are the main reasons why we clone and maintain by our team.

So, if you will apply new patches, please consider to add them to [`magara/active-elastic-job`](https://github.com/magara/active-elastic-job) since we'll some help.

*P.S. Thank you for bringing this :gem: to the Ruby ecosystem, @tawan!*

**Comment by waissbluth** [comment]
@BerkhanBerkdemir did you move that repo to another location? It is a 404 now. Thanks!
