### ISSUE TITLE
Job gets enqueued but code in perform function won't run 

### ISSUE THREAD

**Issue by azazahmed93** [tawan/active-elastic-job#108]
Hi so I followed the docs and I'm stuck at a point where my job gets enqueued but the method perform_later (defined under perform in MyJob) doesn't do anything.

To my understanding after enqueue my worker should perform the task written in the active job.
I am using:

- Rails 5
- ENV['PROCESS_ACTIVE_ELASTIC_JOBS'] set to true
- AWS credentials are set
- Active Job queue adapter set
- Queue name same as the one created in server
- Provided a POST http '/' action in my application returning 200 status

I see my job getting enqueued in the worker logs but job won't execute what its supposed to do even if its a simple puts.

Help me out here I've spent a lot of time on it.
Thanks in advance :)

**Comment by azazahmed93** [comment]
@tawan

**Comment by AdilSarwarNU** [comment]
Facing same issue here!

**Comment by azazahmed93** [comment]
@cbeer @mkozono @mdoza @karensg please if you can help on this issue? I've tried everything.

**Comment by karensg** [comment]
I went through the docs in the readme and it worked for me.
- Dont forget that the release needs to be fixed with the latest commit here: https://github.com/karensg/active-elastic-job
- Set up correct queues in Elastic beanstalk

**Comment by azazahmed93** [comment]
Thanks for the reply @karensg I've added the gem like this:
gem 'active_elastic_job', git: 'https://github.com/tawan/active-elastic-job'
I'll give your repo here now and try.

Our job seems to be enqueued but its not intercepted by Rack I think because It hits the POST http '/' and as per the docs it HTTP post should be ignored.

**Comment by azazahmed93** [comment]
I see worker logs and puts the request body which responded me with this object on worker logs:
{"job_class":"BroadcastEmailJob","job_id":"3a01206b-4322-4ae7-9f34-535d1b4d0fbe","provider_job_id":null,"queue_name":"instagram_queue","priority":null,"arguments":[{"_aj_globalid":"gid://amplifyd/User/843"}],"executions":0,"locale":"en"}

**Comment by karensg** [comment]
Did you set up your worker environment with the correct queue?

**Comment by azazahmed93** [comment]
Yes I have setup a queue 
instagram_queue

and its set in my active job in "queue_as:" parameter too.

Confirmed it from the SQS Queue as well, can see messages in Flight as well.

Problem is they are **NOT** being intercepted by Rack at all and POSTed to HTTP / that is configured in Worker Configuration.  

They above log that I posted are from Worker inside the POST HTTP. 

Ideally they should be intercepted by Rack and **processed**.

**Comment by azazahmed93** [comment]
Issue got resolved I nearly spent 36 hours in this thing.

**[Solution]**
Set:
`config.force_ssl = true` in environment file e.g development.rb

but with this nginx settings in my beanstalk config file  "https-redirect-ruby-puma.config":
`files:
  "/tmp/45_nginx_https_rw.sh":
    owner: root
    group: root
    mode: "000644"
    content: |
      #! /bin/bash

      CONFIGURED=`grep -c "return 301 https" /opt/elasticbeanstalk/support/conf/webapp_healthd.conf`

      if [ $CONFIGURED = 0 ]
        then
          sed -i '/listen 80;/a \    if ($http_x_forwarded_proto = "http") { return 301 https://$host$request_uri; }\n' /opt/elasticbeanstalk/support/conf/webapp_healthd.conf
          logger -t nginx_rw "https rewrite rules added"
          service nginx restart
          exit 0
        else
          logger -t nginx_rw "https rewrite rules already set"
          exit 0
      fi

container_commands:
  00_appdeploy_rewrite_hook:
    command: cp -v /tmp/45_nginx_https_rw.sh /opt/elasticbeanstalk/hooks/appdeploy/enact
  01_configdeploy_rewrite_hook:
    command: cp -v /tmp/45_nginx_https_rw.sh /opt/elasticbeanstalk/hooks/configdeploy/enact
  02_rewrite_hook_perms:
    command: chmod 755 /opt/elasticbeanstalk/hooks/appdeploy/enact/45_nginx_https_rw.sh /opt/elasticbeanstalk/hooks/configdeploy/enact/45_nginx_https_rw.sh
  03_rewrite_hook_ownership:
    command: chown root:users /opt/elasticbeanstalk/hooks/appdeploy/enact/45_nginx_https_rw.sh /opt/elasticbeanstalk/hooks/configdeploy/enact/45_nginx_https_rw.sh`

**Comment by AdilSarwarNU** [comment]
Please close this @azazahmed93
