### ISSUE TITLE
Is this actively maintained?

### ISSUE THREAD

**Issue by AdamT213** [tawan/active-elastic-job#112]
When I add the gem to my gemfile, it says that it depends on aws sdk v2, but I need to support v3. I see a commit in this repository that supposedly updates to support v3,  but rubygems.org lists v2 as a dependency.  Any plans to update any time soon? Thanks.

**Comment by barrywoolgar** [comment]
Until a new version can be tagged and pushed you might have some luck with this:

    gem 'active_elastic_job', github: 'tawan/active-elastic-job', ref: '79444e7'

That'll pin it to just after the commit that made the change you mentioned.

I've not tried it yet, but will do soon.

**Comment by antgel** [comment]
@barrywoolgar How did your tests go? I'm also kind of interested in this gem, but if it's not maintained... :roll_eyes:

**Comment by barrywoolgar** [comment]
Hi @antgel All seems to be working after a month in production, apologies for not updating. 

I've been using the gem for much longer without any issue but I'll probably be going a different route for future AWS/EB projects (not sure what yet though!).

**Comment by jeffxor** [comment]
@barrywoolgar be interested what your route would be

**Comment by barrywoolgar** [comment]
Hi @jeffxor I've not had a similar-sized project yet but if I was trying to stick with EBS and the worker tier, I'd probably just use environment-specific configuration to make the worker instances run Sidekiq and drop SQS altogether. 

There are probably more flexible/fashionable solutions involving docker compose / kubernetes now though!

**Comment by tawan** [comment]
Hi, Author here!

I don't find the time to maintain this gem anymore. Maybe when my son is old enough to go to school I will re-consider, but this is a few years out :)

I'm looking for an organization who is running this code in production and is willing to take over maintaining this gem. If you are part of such organization and think it would be a good fit then please reach out to me either be commenting to this issue or dropping me a an email if you can provide.

Many thanks in advance!

Tawan
