### ISSUE TITLE
not detecting queue

### ISSUE THREAD

**Issue by claudeomusic** [tawan/active-elastic-job#16]
not sure how to handle this. seems it's not detecting my SQS queue? here's the response i get when i try to queue up a job:
 
ActiveJob::QueueAdapters::ActiveElasticJobAdapter::NonExistentQueue: The job is bound to queue at test_queue. Unfortunately a queue
with this name does not exist in this region. Either create an Amazon SQS queue
named test_queue - you can do this in AWS console, make sure to select
region 'us-west-2' - or you select another queue for your jobs.

my queue is https://sqs.us-west-2.amazonaws.com/622149014054/test_queue, so it's definitely not an issue of proper name or region.

**Comment by claudeomusic** [comment]
nevermind! solved it myself. had to assign the proper policy to the role attached to my elasticbeanstalk environment (gave it SQSFullAccess)

**Comment by claudeomusic** [comment]
sorry if that wasn't worded properly. still getting used to the AWS lingo. assigned the SQSFullAccess policy to the instance profile tied to my EC2 instance, to be more accurate

**Comment by tawan** [comment]
Hi @claudeomusic,

Np. The AWS permission system can be confusing. May I ask: did you follow step 3 and step 6 of the [Usage section](https://github.com/tawan/active-elastic-job#usage) without luck and then afterwards added  SQSFullAccess to the instance profile? Maybe I need to update the README.

**Comment by claudeomusic** [comment]
Hi @tawan,

Yes, I did follow that step. Might need to update the README
