### ISSUE TITLE
jobs being repeatedly called

### ISSUE THREAD

**Issue by claudeomusic** [tawan/active-elastic-job#17]
not 100% the source of this issue, but if you can shed any light it's much appreciated. i'm still just trying to make sure everything is wired up properly so i set up a really simple job. for some reason the job seems to keep getting called over and over again.. here's a snippet of the log when i made a second request. i made a call from my webserver console and called UpdateSongJob.perform_later(args)
```

[ActiveJob] [UpdateSongJob] [6b99eb86-3981-4bdf-bfd4-21702fca7c4f] Performing UpdateSongJob from ActiveElasticJob(test_queue) with arguments: "568979ced2b38b05d00003d6", "188.40.62.138", "80"
[ActiveJob] [UpdateSongJob] [6b99eb86-3981-4bdf-bfd4-21702fca7c4f] Performed UpdateSongJob from ActiveElasticJob(test_queue) in 0.48ms
Started POST "/" for 127.0.0.1 at 2016-02-18 11:14:27 +0000
[ActiveJob] [UpdateSongJob] [97ea6055-8940-4d18-a02a-f0911d83509f] Performing UpdateSongJob from ActiveElasticJob(test_queue) with arguments: "5670b6fe7e8482b048000166", "188.40.62.138", "80"
[ActiveJob] [UpdateSongJob] [97ea6055-8940-4d18-a02a-f0911d83509f] Performed UpdateSongJob from ActiveElasticJob((test_queue) in 0.51ms
Started POST "/" for 127.0.0.1 at 2016-02-18 11:14:27 +0000
[ActiveJob] [UpdateSongJob] [c2bde572-73d2-4369-be53-263cd86179c5] Performing UpdateSongJob from ActiveElasticJob(test_queue) with arguments: "5670b6fe7e8482b048000166", "188.40.62.138", "80"
[ActiveJob] [UpdateSongJob] [c2bde572-73d2-4369-be53-263cd86179c5] Performed UpdateSongJob from ActiveElasticJob(test_queue) in 0.38ms
Started POST "/" for 127.0.0.1 at 2016-02-18 11:14:27 +0000
[ActiveJob] [UpdateSongJob] [c41a9f00-4437-4889-a1a7-681777b4dd0f] Performing UpdateSongJob from ActiveElasticJob(test_queue) with arguments: "5670b6fe7e8482b048000166", "188.40.62.138", "80"
[ActiveJob] [UpdateSongJob] [c41a9f00-4437-4889-a1a7-681777b4dd0f] Performed UpdateSongJob from ActiveElasticJob(test_queue) in 0.54ms
Started POST "/" for 127.0.0.1 at 2016-02-18 11:14:27 +0000
[ActiveJob] [UpdateSongJob] [73b93aa3-1903-49ef-9da8-171ed1cce732] Performing UpdateSongJob from ActiveElasticJob(test_queue) with arguments: "5670b6fe7e8482b048000166", "188.40.62.138", "80"
[ActiveJob] [UpdateSongJob] [73b93aa3-1903-49ef-9da8-171ed1cce732] Performed UpdateSongJob from ActiveElasticJob(test_queue) in 0.46ms
Started POST "/" for 127.0.0.1 at 2016-02-18 11:14:28 +0000
[ActiveJob] [UpdateSongJob] [6b99eb86-3981-4bdf-bfd4-21702fca7c4f] Performing UpdateSongJob from ActiveElasticJob(test_queue) with arguments: "568979ced2b38b05d00003d6", "188.40.62.138", "80"
[ActiveJob] [UpdateSongJob] [6b99eb86-3981-4bdf-bfd4-21702fca7c4f] Performed UpdateSongJob from ActiveElasticJob(test_queue) in 0.45ms
```

**Comment by tawan** [comment]
This behavior can have several different causes:

*  the job has not been completed or not reported to the queue as such. Check your logs if the responses return a **200** response code. It should look like this:
```
/var/app/support/logs/access.log
-------------------------------------

127.0.0.1 - - [18/Feb/2016:14:08:17 +0000] "POST / HTTP/1.1" 200 5 "-" "aws-sqsd/2.0"
127.0.0.1 - - [18/Feb/2016:14:08:24 +0000] "POST / HTTP/1.1" 200 5 "-" "aws-sqsd/2.0"
```

* the _Visibility timeout setting_ is too optimistic. The queue will wait for so long for a response that the job has been successfully processed. If there is no response within this time window (for example the job takes longer), than the queue makes the job available again. You can find this setting here: select your woker environment -> Configuration -> Worker configuration.

I can tell you more if you paste the log snippet from the `/var/app/support/logs/access.log` part.

Hope that helps,

tawan

**Comment by claudeomusic** [comment]
ah, i see. yeah looks like i'm getting a 500 error, and i set a pretty high visibility timeout so it keeps retrying. a little confused on how to move forward still, though.

127.0.0.1 - - [18/Feb/2016:10:38:35 +0000] "POST / HTTP/1.1" 500 193 "-" "aws-sqsd/2.0" "-"
127.0.0.1 - - [18/Feb/2016:10:38:36 +0000] "POST / HTTP/1.1" 500 193 "-" "aws-sqsd/2.0" "-"
127.0.0.1 - - [18/Feb/2016:10:38:37 +0000] "POST / HTTP/1.1" 500 193 "-" "aws-sqsd/2.0" "-"
127.0.0.1 - - [18/Feb/2016:10:38:38 +0000] "POST / HTTP/1.1" 500 193 "-" "aws-sqsd/2.0" "-"
127.0.0.1 - - [18/Feb/2016:10:38:39 +0000] "POST / HTTP/1.1" 500 193 "-" "aws-sqsd/2.0" "-"
127.0.0.1 - - [18/Feb/2016:10:38:40 +0000] "POST / HTTP/1.1" 500 193 "-" "aws-sqsd/2.0" "-"
127.0.0.1 - - [18/Feb/2016:10:38:41 +0000] "POST / HTTP/1.1" 500 193 "-" "aws-sqsd/2.0" "-"
127.0.0.1 - - [18/Feb/2016:10:38:42 +0000] "POST / HTTP/1.1" 500 193 "-" "aws-sqsd/2.0" "-"
127.0.0.1 - - [18/Feb/2016:10:38:43 +0000] "POST / HTTP/1.1" 500 193 "-" "aws-sqsd/2.0" "-"
127.0.0.1 - - [18/Feb/2016:10:38:44 +0000] "POST / HTTP/1.1" 500 193 "-" "aws-sqsd/2.0" "-"
127.0.0.1 - - [18/Feb/2016:10:38:45 +0000] "POST / HTTP/1.1" 500 193 "-" "aws-sqsd/2.0" "-"
127.0.0.1 - - [18/Feb/2016:10:38:46 +0000] "POST / HTTP/1.1" 500 193 "-" "aws-sqsd/2.0" "-"
127.0.0.1 - - [18/Feb/2016:10:38:47 +0000] "POST / HTTP/1.1" 500 193 "-" "aws-sqsd/2.0" "-"
127.0.0.1 - - [18/Feb/2016:10:38:48 +0000] "POST / HTTP/1.1" 500 193 "-" "aws-sqsd/2.0" "-"
127.0.0.1 - - [18/Feb/2016:10:38:49 +0000] "POST / HTTP/1.1" 500 193 "-" "aws-sqsd/2.0" "-"
127.0.0.1 - - [18/Feb/2016:10:38:50 +0000] "POST / HTTP/1.1" 500 193 "-" "aws-sqsd/2.0" "-"

**Comment by tawan** [comment]
Yea, there is an error while the job is performed. Your issue brought my attention to how the gem handles errors and until now it did it wrong. It just responds with 500 but then leaves no traces in the logs.

I fixed that and released a new version (1.4.2).
You should update to the new version with
```bash
bundle update active_elastic_job
```
commit the updated `Gemfile.lock` file and deploy again.
With the new version you should have more infos in the logs on what actually isn't working.
You should then check the section below
```
-------------------------------------
/var/app/support/logs/production.log
-------------------------------------
```

:+1:  Thanks for posting your problems, your feedback helps to make this gem more stable.

**Comment by claudeomusic** [comment]
perfect, thankyou! super glad to have discovered this gem

**Comment by ACPK** [comment]
@claudeomusic - How did you get it to stop running?
