### ISSUE TITLE
managing priority?

### ISSUE THREAD

**Issue by claudeomusic** [tawan/active-elastic-job#18]
sorry i'm throwing so many questions at you! 

as it's built now, how i understand it is that it's a first-come-first-serve type of model. is there a way to manage the priority of tasks? i.e. if i have a long queue of tasks running, is there a way i can then shoot off an e-mail asynchronously without too much delay? or, in this scenario, would i have to setup a separate background worker and queue purely for e-mails?

-chris

**Comment by AlexanderUlitin** [comment]
Hi @claudeomusic, I'm not a pro with SQS I think you should use separated SQS queue for Urgent tasks, it will fits with your requirements and perform urgent job without delays. I don't know other way to set priority for the task.

**Comment by tawan** [comment]
@AlexanderUlitin is right. You will need to setup another worker environment with its own queue for your email jobs.

**Comment by claudeomusic** [comment]
@AlexanderUlitin @tawan :+1:
