### ISSUE TITLE
Priority

### ISSUE THREAD

**Issue by ruuts** [tawan/active-elastic-job#20]
Hi @tawan!

Any idea how to implement some sort of priority system for messages?
With delayed job you can give the job a priority. So it will be processed with precedence above others.

In Beanstalk I can imagine the following:
- Make multiple worker environments
- One with more app servers than the other so jobs will be processed quicker.
- Send jobs to a different queues.

Is there a better way?

**Comment by tawan** [comment]
Hi @ruuts,
 I would implement it as you have explained it. Amazon SQS does not provide a mechanism to change the order of messages in a queue itself. I also think that the docs mention that your approach is the way to go.

You can also play with the auto-scale settings. If load increases, let the worker env spawn more instances. Maybe it also makes sense to have a queue for fast running jobs (like emails), and a queue for heavy slow jobs.

In the end it depends on the budget. Each additional worker environment means at least one EC2 micro instance.

**Comment by ruuts** [comment]
@tawan alright thanks for the info! I think we will start of with one queue and fine tune when everything is being used in production.
