### ISSUE TITLE
No route matches [POST] "/"

### ISSUE THREAD

**Issue by MikeIsMe** [tawan/active-elastic-job#27]
Hi,

First off, thanks for making this Gem.  It's just what we needed.  Currently I am in the process of getting this setup on AWS (Elastic Beanstalk).  For our application it's being used to send email asynchronously.

The messages are getting enqueued correctly but during dequeuing by the worker environment it has the following error:

 -------------------------------------
/var/app/containerfiles/logs/production.log
-------------------------------------
I, [2016-04-01T01:03:37.421909 #9616]  INFO -- : Started POST "/" for 127.0.0.1 at 2016-04-01 01:03:37 +0000
F, [2016-04-01T01:03:37.554981 #9616] FATAL -- : 
ActionController::RoutingError (No route matches [POST] "/"):

Any ideas?

Thanks in advance,
Mike

**Comment by tawan** [comment]
Hi, thanks for reporting the issue.

Please check these two settings:

* The gem is added to to bundle and deployed to the **worker** environment.
* The environment variable `DISABLE_SQS_CONSUMER` in the **worker** environment is **not** set at all or set to `false`.

If both settings comply, then I'd ask you to post the content of `var/app/support/logs/access.log`.

The general problem is that the middleware does not intercept the requests from the aws-sqs daemon and the request it passed through to your rails app.

**Comment by MikeIsMe** [comment]
Hi,

Thanks for getting back to me.  I verified that the Gem does exist in the worker environment (version 1.4.3).  I also verified that the environment variable DISABLE_SQS_CONSUMER does NOT exist in the worker environment.

I wasn’t able to find the log file you mentioned on AWS.  There isn’t a support direction under /var/app.  Only containerfiles and current directories.  I looked inside of both and could not find a access.log.

FYI, the environment is Ruby 2.0 (puma).

Any thoughts?

Thanks
Mike


On Apr 1, 2016, at 5:15 AM, Tawan Sierek <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, thanks for reporting the issue.

Please check these two settings:

  *   The gem is added to to bundle and deployed to the worker environment.
  *   The environment variable DISABLE_SQS_CONSUMER in the worker environment is not set at all or set to false.

If both settings comply, then I'd ask you to post the content of var/app/support/logs/access.log.

The general problem is that the middleware does not intercept the requests from the aws-sqs daemon and the request it passed through to your rails app.

**Comment by claudeomusic** [comment]
most of the logs can be found in /var/log or through the eb console from my understanding. i'm assuming you're running on nginx so your access.log would be at /var/log/nginx/access.log

**Comment by MikeIsMe** [comment]
Hi,

Yes, I found the logs in /var/log/nginx/access.log.  Here are the contents:

127.0.0.1 - - [01/Apr/2016:19:42:21 +0000] "POST / HTTP/1.1" 404 1318 "-" "aws-sqsd/1.1" "-"
127.0.0.1 - - [01/Apr/2016:19:47:21 +0000] "POST / HTTP/1.1" 404 1318 "-" "aws-sqsd/1.1" "-"
127.0.0.1 - - [01/Apr/2016:22:55:40 +0000] "POST / HTTP/1.1" 404 1318 "-" "aws-sqsd/1.1" "-"
127.0.0.1 - - [01/Apr/2016:23:00:40 +0000] "POST / HTTP/1.1" 404 1318 "-" "aws-sqsd/1.1" "-"
127.0.0.1 - - [01/Apr/2016:23:05:40 +0000] "POST / HTTP/1.1" 404 1318 "-" "aws-sqsd/1.1" "-"
127.0.0.1 - - [01/Apr/2016:23:10:40 +0000] "POST / HTTP/1.1" 404 1318 "-" "aws-sqsd/1.1" "-"
127.0.0.1 - - [01/Apr/2016:23:15:40 +0000] "POST / HTTP/1.1" 404 1318 "-" "aws-sqsd/1.1" "-"
127.0.0.1 - - [01/Apr/2016:23:20:40 +0000] "POST / HTTP/1.1" 404 1318 "-" "aws-sqsd/1.1" "-"
127.0.0.1 - - [01/Apr/2016:23:21:43 +0000] "POST / HTTP/1.1" 404 1318 "-" "aws-sqsd/1.1" "-"
127.0.0.1 - - [01/Apr/2016:23:26:43 +0000] "POST / HTTP/1.1" 404 1318 "-" "aws-sqsd/1.1" “-"



Thanks
Mike


On Apr 1, 2016, at 2:28 PM, Chris Changchien <notifications@github.com<mailto:notifications@github.com>> wrote:


most of the logs can be found in /var/log or through the eb console from my understanding. i'm assuming you're running on nginx so your access.log would be at /var/log/nginx/access.log

**Comment by tawan** [comment]
Your worker environment still uses the AWS SQS daemon version 1 -> `aws-sqsd/1.1`
This gem makes use of message attributes, but these are only supported by version 2. Is it possible for you to switch to a newer platform? I tried the Ruby 2.0 (Puma) but with the newest Amazon Linux 2015 v.2.0.8. and it worked fine.

**Comment by MikeIsMe** [comment]
Once again, thanks for your help tracking the issue down.  It may be a challenge for us to move our application to the latest and greatest AWS, but we will give it a try.  Thanks again.

**Comment by lucienLopez** [comment]
it can also happen if you forgot to set PROCESS_ACTIVE_ELASTIC_JOBS to true

**Comment by srladuani** [comment]
> it can also happen if you forgot to set PROCESS_ACTIVE_ELASTIC_JOBS to true

Hi @lucienLopez 
It really helped me a lot. Thanks a lot
