### ISSUE TITLE
Rails 5 Issue?

### ISSUE THREAD

**Issue by mdoza** [tawan/active-elastic-job#28]
Checking this Gem out on Rails 5, the following error occurs when attempting to `#perform_later`:

> NoMethodError (undefined method `enqueue' for #<ActiveJob::QueueAdapters::ActiveElasticJobAdapter:0x00558d3e366bd8>):

Odd since the method does exist.

Just wanted to give a heads up. When I have some time, I'll try to help resolve the issue.

**Comment by tawan** [comment]
Hi @mdoza ,

Thanks for reporting the issue. Rails 5 is still an open topic that hasn't been addressed, yet. I definitely welcome all further input for making this gem Rails 5 ready.

**Comment by mdoza** [comment]
Submitted PR #29

**Comment by mdoza** [comment]
PR #29 merged.
