### ISSUE TITLE
Support AWS_SECRET_KEY as well

### ISSUE THREAD

**Issue by ngan** [tawan/active-elastic-job#31]
The AWS Ruby SDK supports all three:
`AWS_SECRET_ACCESS_KEY`, `AMAZON_SECRET_ACCESS_KEY`, `AWS_SECRET_KEY`

It would be great if this gem followed suit. Wouldn't complicate the code too much and you wouldn't have to mention it in docs too prominently either. Also, When creating a new worker environment, the configuration says:

![screen shot 2016-04-21 at 12 32 27 am](https://cloud.githubusercontent.com/assets/16579/14701143/900a948e-0758-11e6-9f91-e3eafa8a1e13.png)

**Comment by tawan** [comment]
cool, this goes into the next release. Thx @ngan
