### ISSUE TITLE
Using instance profile credentials?

### ISSUE THREAD

**Issue by cbeer** [tawan/active-elastic-job#33]
The README says to explicitly configure the SQS Client connection:

```
- Add AWS_ACCESS_KEY_ID and set it to access key id of the newly created user (from Step 3).
- Add AWS_SECRET_ACCESS_KEY and set it to the secret access key of the newly created user (from Step 3).
- Add AWS_REGION and set it to the region of the SQS queue, created in Step 2.
```

Is it possible to use the implicit instance profile credentials when running in EC2? It seems like the environment-based configuration is pretty hard-coded, but maybe you can suggest an approach that would work?

**Comment by tawan** [comment]
@cbeer  Starting with version 2.0.0 the gem uses instance profiles per default.
