### ISSUE TITLE
Perform more than 15 minutes later

### ISSUE THREAD

**Issue by mkozono** [tawan/active-elastic-job#34]
We want to be able to run jobs at a specific time in the future. Since AWS SQS doesn't allow delays more than 15 minutes, we can't do this:
```
GuestsCleanupJob.set(wait_until: Date.tomorrow.noon).perform_later(guest)
```
Anybody else need this functionality? What did you do?

**Comment by zaaroth** [comment]
@tawan might have a different opinion, but I see this gem as an "instant job queue". SQS is not meant to be a "cron" scheduler, so I guess this gem is not as well. SQS/Worker envs are mostly used to offload async jobs that are part of larger tasks performed on a web environment or so.

In your case it seems you would need a real scheduler to, when the right time comes, use elastic job to actually run the job right away.

**Comment by mkozono** [comment]
Agreed. Unfortunately this means I lose a lot of the simplicity I gained by choosing ActiveElasticJob.

So what I'm looking at now is partially duplicating delayed_job functionality:
1. Queue jobs into a scheduled_jobs table
2. Use `cron.yaml` to run SchedulerJob every minute
3. SchedulerJob checks the table and runs or queues jobs

Does this sound crazy? I'm considering switching to delayed_job even though most examples get a little hacky somewhere.

**Comment by zaaroth** [comment]
active elastic job is really good at instant jobs, ensuring they are not forgotten (SQS) and that you have capacity to run them (elastic beanstalk). If most of your jobs are not instant then, perhaps, active elastic job might not be the best choice for the task (unless you use a lot of capacity to run your tasks, than it is worth chanining another gem with this one to leverage elastic beanstalk).

**Comment by mkozono** [comment]
Thanks @zaaroth I think I'm just reluctant to get into those obscure eb extensions etc. We probably won't have massive volume so we should probably switch to a different solution.

I'm still interested to hear what anyone else has done though.

**Comment by tawan** [comment]
Hi @mkozono,

You and @zaaroth  are correct.
I will try to sum up and propose a solution:

Must we really frame the `GuestsCleanUpJob` as a job that has to be queued after a specific event has happened? 
Or maybe it is sufficient to look at it as a periodic job that runs every day at noon? I'm thinking of something like this:

```ruby
# invoke this method every day within a cronjob
def run_everyday
  guests = Guest.where(dirty: true)

  guests.each { |guest| guest.clean_up }
end
```

If this would work for you, then you don't need this gem actually. You just need to set up the worker environment with an attached SQS queue if you haven't already. Then, as you mentioned, you add a `cron.yaml` file to your project's root folder as described in the [AWS documentation](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features-managing-env-tiers.html#worker-periodictasks). Inside the `cron.yaml` you specify the URL that you should be called at noon. Add a controller with an action that listens to this URL. Inside the action you can invoke a method, like the one in my example.

**Comment by zaaroth** [comment]
@tawan wouldn't that cause any trouble in case you have 2+ worker environments? I think it could overlap jobs.

**Comment by mkozono** [comment]
@tawan actually we have decided to do something similar to your suggestion (GuestCleanupJob is just an example). But I fear that we are only delaying the issue for ourselves. I'm glad you mentioned this reframing of the problem though.

@zaaroth I believe AWS ensures this is not an issue with cron.yaml. Only one SQS message would be queued at the right time.

**Comment by tawan** [comment]
@zaaroth  Not really. You can actually re-use the same worker environment. Active Elastic Job ignores jobs from the queue that do not origin from the gem itself.
