### ISSUE TITLE
cat: /proc/1/cgroup: No such file or directory

### ISSUE THREAD

**Issue by yeonhoyoon** [tawan/active-elastic-job#35]
[Due to the code checking for docker container](https://github.com/tawan/active-elastic-job/blob/2cbacc79c5f3f71bd1306f119f57abe2ed0b1416/lib/active_elastic_job/rack/sqs_message_consumer.rb#L22), the following message gets printed to the console whenever you run rails/rake commands.
```cat: /proc/1/cgroup: No such file or directory```

**Comment by tawan** [comment]
👍 I'll have a look at that. Thx

**Comment by tawan** [comment]
@mkozono Does your commit solve this issue? If so, do you want to make a pull request?

**Comment by mkozono** [comment]
Sure, I just submitted #36.

**Comment by tawan** [comment]
Thx a lot @mkozono 

Merged and released
