### ISSUE TITLE
HTTP Error 301

### ISSUE THREAD

**Issue by peterkle** [tawan/active-elastic-job#37]
Hi, I am getting a 301 error in my worker env logs, any idea why?

var/app/support/logs/access.log
`127.0.0.1 - - [28/May/2016:02:04:30 +0000] "POST / HTTP/1.1" 301 5 "-" "aws-sqsd/2.0"`

/var/log/aws-sqsd/default.log
```
2016-05-28T02:07:33Z message: sent to %[http://localhost:80]
2016-05-28T02:07:33Z http-err: 3d762187-16aa-409e-aa6f-ba21f2a2962a (995) 301 - 0.004
```

**Comment by tawan** [comment]
Hi @peterkle 

Is this issue still present? The gem's only responses are either `200` or `403` or it passes the request through to the rails stack. Given the response is `301` then this means that the request is passed through. Since the agent string is correct, I suspect that the request originates from a job in the queue which has not been enqueued by this gem. I'd recommend to check this possibility.

Cheers and thanks for the submission,

Tawan

**Comment by sauy7** [comment]
@peterkle Has your worker app been configured to force SSL in config/production.rb?

```
# Force all access to the app over SSL, use Strict-Transport-Security, and use secure cookies.
config.force_ssl = true
```

If so, the request to localhost:80 is being 301 redirected to localhost:443.

**Comment by briantigerchow** [comment]
@sauy7, this may be slightly off-topic, but I'm curious how you managed to force ssl behind the ELB while avoiding infinite redirect loop and also passing health checks. I'm assuming you're on Elastic Beanstalk with an auto-scaling group.

**Comment by sauy7** [comment]
I didn't force SSL. I have a separate production_worker Rails environment for my worker tier. My Web tier (production environment) does force SSL. I've not yet setup health checks although that is something I will be looking at next (comments in issue #32 suggests a solution, do they not?)

Also off-topic: Whilst running separate Rails environments for the separate tiers may seem like overkill, I have other reasons for doing so (e.g., .ebextensions differ between the two tiers). I manage both tiers from a single codebase and branch and have created a custom rake task to deploy different artefacts (zip archives) from the same codebase (the worker tier excludes a subset of .ebextensions, the web tier excludes the cron.yml file).

**Comment by tawan** [comment]
@peterkle Do you enforce SSL in the worker tier? If so, make sure that you use the latest version of this gem. We had an issue before version 1.4.4 but [it had been fixed now](https://github.com/tawan/active-elastic-job/commit/27efeef3dd987b72308342dbe5d67ec694348752).
