### ISSUE TITLE
Deprecation in Rails 5

### ISSUE THREAD

**Issue by karensg** [tawan/active-elastic-job#38]
Hi, so far I can see, everything works in Rails 5. There is one little deprecation:

```
DEPRECATION WARNING: Passing strings or symbols to the middleware builder is deprecated, please change
them to actual class references.  For example:

  "ActiveElasticJob::Rack::SqsMessageConsumer" => ActiveElasticJob::Rack::SqsMessageConsumer
```

**Comment by tawan** [comment]
Hi @karensg ,

Thanks for the submission. If you are up for  a PR I'd be happy to merge.

Cheers,

tawan

**Comment by karensg** [comment]
The Travis test failed, but I think that the error is unrelated or I am wrong?

**Comment by tawan** [comment]
Yes,  tests always fail on PRs at the moment. Please ignore it for now. I
will have a look at the PR soon. Thanks a lot for the submission.

On Tue, Jul 12, 2016 at 9:59 PM, Karens <notifications@github.com> wrote:

> The Travis test failed, but I think that the error is unrelated or I am
> wrong?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/tawan/active-elastic-job/issues/38#issuecomment-232161264>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAZm1ySR6webMekHjpgsstm6HWefAIDks5qU_IGgaJpZM4JG9nO>
> .
>



-- 
*Tawan SIEREK*

Phone:    +43 650 700 20 12
Email:     tawan.sierek@gmail.com
Address: Margaretenstraße 61/3 | 1050 Vienna | Austria
Skype:   Tawan Sierek

**Comment by antonioparisi** [comment]
Hi @tawan, I notice that the last version is `1.6.1 - May 24, 2016` - would be greato to bump the version and release a new version including also this deprecation fix, thanks. 👍
