### ISSUE TITLE
Allow user to configure gem in initializer

### ISSUE THREAD

**Issue by briantigerchow** [tawan/active-elastic-job#42]
I would like to be able to configure my AEJ user independently from the AWS users required by other gems. This is not possible because this gem uses `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables. As it stands, this configuration requirement dictates that I must give multiple permissions to a AWS single user.

I want to be able to configure this gem in an initializer like so:

``` ruby
ActiveElasticJob.setup do |config|
  config.aws_access_id = ENV.fetch("AEJ_ACCESS_ID")
  config.aws_secret_key = ENV.fetch("AEJ_SECRET_KEY")
  config.aws_region = ENV.fetch("AEJ_REGION")
  config.disable_sqs_consumer = ENV.fetch("DISABLE_SQS_CONSUMER")
end
```

**Comment by btc** [comment]
Thank you for adding this feature.
