### ISSUE TITLE
403 error, same secrete base key

### ISSUE THREAD

**Issue by caseygipson** [tawan/active-elastic-job#49]
`2016-11-15T17:44:50Z message: sent to http://localhost:80`
`2016-11-15T17:44:50Z http-err: 2dd429b5-be92-4cc5-bdaf-92e7ba41bc8e (1) 403 - 0.004`

I'm getting a request from localhost but still getting a 403, I have the same secret key base for web and worker tiers. Any tips for debugging or things I may have missed?

**Comment by caseygipson** [comment]
Update, it turns out it was an rack env mixup, now all is well. Thanks for building this!!!

**Comment by lovesmall** [comment]
Hello @caseygipson , I have this same issue today. May I know how exactly you solve it ?

**Comment by joselo** [comment]
Hey guys any idea how to solve this I still have a 403 error :(

**Comment by AdilSarwarNU** [comment]
@caseygipson I am facing the same issue, we're getting 200 on / on our development environment 
but on our Prod Environment it throughts 403. 

The configs for Rack are identical.

**Comment by caseygipson** [comment]
@AdilSarwarNU A few things to check, SQS permissions, name of the queue is provided via queue_as in your job, and config.active_job.queue_adapter = :active_elastic_job is set.
