### ISSUE TITLE
ArgumentError: wrong number of argument (given 1, expected 2)

### ISSUE THREAD

**Issue by AhmedLoud** [tawan/active-elastic-job#50]
Hello, I tried to follow straight all the documentation for configuring my queue and my application.
However I have an error with the following log: 
ArgumentError: wrong number of arguments (given 1, expected 2)
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/active_elastic_job-2.0.0/lib/active_job/queue_adapters/active_elastic_job_adapter.rb:53:in `initialize'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/active_elastic_job-2.0.0/lib/active_job/queue_adapters/active_elastic_job_adapter.rb:145:in `exception'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/active_elastic_job-2.0.0/lib/active_job/queue_adapters/active_elastic_job_adapter.rb:145:in `raise'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/active_elastic_job-2.0.0/lib/active_job/queue_adapters/active_elastic_job_adapter.rb:145:in `rescue in queue_url'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/active_elastic_job-2.0.0/lib/active_job/queue_adapters/active_elastic_job_adapter.rb:139:in `queue_url'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/active_elastic_job-2.0.0/lib/active_job/queue_adapters/active_elastic_job_adapter.rb:122:in `build_message'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/active_elastic_job-2.0.0/lib/active_job/queue_adapters/active_elastic_job_adapter.rb:96:in `enqueue_at'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/active_elastic_job-2.0.0/lib/active_job/queue_adapters/active_elastic_job_adapter.rb:90:in `enqueue'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/active_elastic_job-2.0.0/lib/active_job/queue_adapters/active_elastic_job_adapter.rb:81:in `enqueue'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activejob-5.0.0.1/lib/active_job/enqueuing.rb:76:in `block in enqueue'

Do you know how I did wrong ?

Thanks for helping.

**Comment by AhmedLoud** [comment]
Fixed . 
I have put the name of the queue in the wrong place. 

I directly put this in the configuration.
config.action_mailer.deliver_later_queue_name = 'awseb-e-cfh****....'

**Comment by tawan** [comment]
Hi @AhmedLoud 

Thanks for your submission. I will look into that.

**Comment by smarquez1** [comment]
I'm getting a similar error, probably because I misconfigured the queue. 

I think this line should include the aws_region, because `NonExistentQueue` expects two arguments: https://github.com/tawan/active-elastic-job/blob/master/lib/active_job/queue_adapters/active_elastic_job_adapter.rb#L145
