### ISSUE TITLE
2.0 config issue (possible)

### ISSUE THREAD

**Issue by lovesmall** [tawan/active-elastic-job#51]
Hello,

I've upgraded to 2.0 and the periodic tasks is very useful. However I notice a possible issue from commit of "Simplify configuration". 

[Aws credential ](https://github.com/tawan/active-elastic-job/blob/39a221bac714f6f87c502c18ccb8ecef0521097b/lib/active_elastic_job/railtie.rb) setting, this line : 

`    config.active_elastic_job.aws_credentials = Aws::InstanceProfileCredentials.new
`

1. It seems very slow. (my small app takes obviously much longer time to start after upgrade to 2.0)
2. It seems not working and I have to set the credential manually like 

`  config.active_elastic_job.aws_credentials = Aws::Credentials.new(Rails.application.secrets.aws_key_id, Rails.application.secrets.aws_key_secret)
`

I'm not 100% sure but looks like a problem.  Thanks for any help.

**Comment by tawan** [comment]
Hi @lovesmall Thanks for the feedback! I will look into it.

**Comment by lovesmall** [comment]
Hello @tawan , I've read aws docs but didn't quite get the idea of this InstanceProfileCredential. Do you have any guide on using this ? Show we pass in any parameters ? So far I can confirm it (alone) takes near 40 seconds during my server starts. (which is really bad =,= )

Maybe we can use the popular ways to set the aws_credential like many other gems ?

Thanks and this is a very useful gem = ]

**Comment by agirling** [comment]
I am also noticing this issue with 2.0.0.  On a pristine rails app:

version 2.0.0 - "time rake -T"
```
real    0m39.154s
user    0m1.468s
sys     0m0.228s
```

version 1.7.0 - "time rake -T"
```
real    0m1.701s
user    0m1.492s
sys     0m0.192s
```

**Comment by tawan** [comment]
Hi @lovesmall ,

Thanks for your submission.

I hope I can clarify your issues.
So the default configuration is:
```Ruby
config.active_elastic_job.aws_credentials = Aws::InstanceProfileCredentials.new
```
To make this work, you have to give your EC2 instances the right permissions. You can do that by attaching the **AmazonSQSFullAccess** policy to the role which is assigned to the EC2 instances in your web environment in Elastic Beanstalk. Please have a look at step 3 in the [Usage Guide](https://github.com/tawan/active-elastic-job#usage). Please let me know if this step is unclear, I will update the README in that case.

Now, if your application runs on Elastic Beanstalk on EC2 Instances, then `Aws::InstanceProfileCredentials.new` will automatically retrieve valid credentials for the role that is assigend to the EC2 instance. If this role has the right permissions (**AmazonSQSFullAccess**), then this gem is able to send messages to your Amazon SQS queue through the official Ruby AWS client used by this gem.

I chose this approach as the default one for security reasons. It makes use of AWS' IAM service which allows you to manage credentials within AWS itself. As you can see, no AWS Key and AWS ID need to be passed to the  configuration. Whereas in your approach you have to worry about storing the credentials somewhere and make them available. As far as I can guess from your example, it seems that you keep them the default Rails `config/secrets.yml` file. If this file is checked in into your git repository, then the AWS credentials are available to anyone who has reading access to the repository. This makes it harder for you the control access to the credentials and prevent unauthorized usage of your AWS resources.

**Comment by tawan** [comment]
Hi @agirling @lovesmall 

Thanks for your submission.

My guess is that the long startup happens on your local machine when you startup the application for development. Can you confirm?

In this case, I will definitely have to do something about it. Probably I will make the configuration of the AWS credentials lazy loading.

Cheers,

Tawan

**Comment by lovesmall** [comment]
Hi @tawan 

Thank you for the explanation. 

I think it is a very elegant solution for the aws credential generation. Just that if it happens on local dev, this will takes a very long time (due to timeout maybe?)

As for my current solution, I store aws keys in the elastic beanstalk software configuration (access them as Env variable). So they are not in the github. But still, I think your way looks even better and I'll try it again.

Making it lazy load definitely solve this issue. Thanks again.
