### ISSUE TITLE
How to run on local environment

### ISSUE THREAD

**Issue by khiem-nguyen** [tawan/active-elastic-job#52]
I want to test elastic job on my local pc. How can I do it?

**Comment by lovesmall** [comment]
I think you can't test it on local pc as this gem is used to manage job(via aws SQS) between web tier and worker tier.

I config ` config.active_job.queue_adapter = :inline` for my dev and `config.active_job.queue_adapter = :active_elastic_job` for my production.

**Comment by khiem-nguyen** [comment]
thank alot

**Comment by tawan** [comment]
@khiem-nguyen Yes, @lovesmall  is right. You can't test it in a local environment, but as @lovesmall  already mentioned, you can configure the `:inline` adapter for local testing.

Thx @lovesmall
