### ISSUE TITLE
Pausing Jobs

### ISSUE THREAD

**Issue by ACPK** [tawan/active-elastic-job#53]
If we experience a bug / issue, how can we pause a set of jobs?

**Comment by tawan** [comment]
Hi @ACPK,

Depending on your needs, but you could just stop the worker environment. Jobs would be still enqueued in the queue. However, after you have fixed the bug, you can start the worker environment again, and it will pick up jobs from the queue again. But please, be advised, a queue can get full, if no jobs are retrieved from the queue for a certain time.
