### ISSUE TITLE
Litmit number of concurrency jobs

### ISSUE THREAD

**Issue by khiem-nguyen** [tawan/active-elastic-job#59]
How to  limit number of concurrency job.

Worker instances only has enough resources for about 10 concurrently jobs.
But it receives more than these number of requests so it cannot handle all of them

Please help to prevent it

**Comment by tawan** [comment]
Hi @khiem-nguyen ,

Did you find a solution? In case you are still looking, there has been a similar issue. I think the answer might help in your case: https://github.com/tawan/active-elastic-job/issues/47

Cheers,

Tawan
