### ISSUE TITLE
Current Travis build is broken

### ISSUE THREAD

**Issue by pablonahuelgomez** [tawan/active-elastic-job#79]
Please see: https://travis-ci.org/tawan/active-elastic-job

Would like to help fixing these specs. Seems that they're coupled to a specific AWS account.

**Comment by tawan** [comment]
Hi, thanks for offering your help. I'm currently working on automating the bootstrapping of EB environments. This would allow to run  the travis builds independently.

**Comment by tawan** [comment]
Hi @pablonahuelgomez,
Travis builds launches now the necessary elastic beanstalk environments. Therefore, issuing a PR and triggering a Travis build is probably the easiest way to test the integration with AWS EB. If you want to run a subset of specs that do not require a launched EB environment, before issuing a PR, you can do so:

 ```bash
 EXCEPT_DEPLOYED=true bundle exec rspec spec
 ```

**Comment by pablonahuelgomez** [comment]
Thanks @tawan that looks great!
