### ISSUE TITLE
ActiveJob::QueueAdapters::ActiveElasticJobAdapter::SerializedJobTooBig

### ISSUE THREAD

**Issue by puneetpandey** [tawan/active-elastic-job#86]
Hi,

I am using `active_elastic_job` gem and have installed and configured web environment and worker environment successfully.

When I try to send image data to background I get:

    I, [2018-04-09T16:04:29.215625 #9708]  INFO -- : [f5b04fe1-15a6-4ee3-bdf6-ef3ed395a3c5] Completed 401 Unauthorized in 10763ms (ActiveRecord: 0.0ms)
    F, [2018-04-09T16:04:29.216187 #9708] FATAL -- : [f5b04fe1-15a6-4ee3-bdf6-ef3ed395a3c5]   
    F, [2018-04-09T16:04:29.216221 #9708] FATAL -- : [f5b04fe1-15a6-4ee3-bdf6-ef3ed395a3c5] ActiveJob::QueueAdapters::ActiveElasticJobAdapter::SerializedJobTooBig (            The job contains 322466 bytes in its serialzed form,
            which exceeds the allowed maximum of 262144 bytes imposed by Amazon SQS.
    ):

Can I handle this configuration from the codebase or Can i increase this limit from SQS Dashboard? Currently, I can see `Maximum Message Size: | 256 KB` set for my queue. Please help!

**Comment by puneetpandey** [comment]
I came across with this link: https://github.com/awslabs/amazon-sqs-java-extended-client-lib but not sure if I can use it in my rails app! Please advise.

**Comment by SleeplessByte** [comment]
No. This is an Amazon Limit. 

https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-limits.html#limits-queues

Instead, you could send your job parameters to S3 and only send a pointer as your message. Then, in the job, retrieve the data from S3 using the pointer.

**Comment by joeyparis** [comment]
Closing as this is a limitation of Amazon SQS and not directly a problem with this gem.
