### ISSUE TITLE
Support for AWS SDK v3?

### ISSUE THREAD

**Issue by steveclarkin** [tawan/active-elastic-job#90]
Any plans to support AWS SDK v3?

I see there was a PR here #88

**Comment by lautarocastillo** [comment]
Does it work with Active Storage?

**Comment by degendra** [comment]
@lautarocastillo @steveclarkin  Current master version support AWS SDK v3. To support Active Storage you need to either create a default queue on SQS or configure active storage default queue:

**`config.active_storage.queue = :queue_name`**

**Comment by joeyparis** [comment]
Version 3 of active-elastic-job is set to support AWS SDK v3. I also believe degendra's solution will work to solve lautarocastillo's question so I am going to close this issue.
