### ISSUE TITLE
Specify queue for a periodic task

### ISSUE THREAD

**Issue by YoranBrondsema** [tawan/active-elastic-job#98]
Suppose I have 2 worker environments, corresponding to the queues `high` and `low`. Will the periodic tasks that are defined in `cron.yaml` run in both environments? Or will the queue that is defined in the job definition of the task be respected? This isn't entirely clear to me from [the documentation](https://github.com/tawan/active-elastic-job#set-up-periodic-tasks-cron-jobs).

**Comment by bookmebus** [comment]
I think you can specify the queue name in your ActiveJob class definition instead.

**Comment by YoranBrondsema** [comment]
Thanks for the reply @bookmebus. Yes figured that out in the end. Will close the issue.
